### ISSUE TITLE
[vuepress]: cannot resolve plugin "mathjax"

### ISSUE THREAD

**Issue by zirnc** [Shigma/vuepress-plugin-mathjax#11]
I can't use this plugin.
![](https://i.loli.net/2019/06/04/5cf64428cdd5425479.png)

Here's my config:
```javascript
···
    'mathjax': { 
      target: 'svg',
      presets: [
        '\\def\\lr#1#2#3{\\left#1#2\\right#3}',
      ],
    },
···
```

Here's my `package.json`:
```json
{
  "name": "chungzh-blog",
  "description": "ChungZH's blog",
  "author": "ChungZH <chung.zh@qq.com>",
  "license": "MIT",
  "version": "5.0.0",
  "scripts": {
    "dev": "cross-env NODE_ENV=development vuepress dev src --temp ./.temp",
    "build": "cross-env NODE_ENV=production vuepress build src -d ./dist --temp ./.temp"
  },
  "dependencies": {
    "@vssue/vuepress-plugin-vssue": "^0.5.1",
    "@vuepress/plugin-back-to-top": "^1.0.0-alpha.35",
    "@vuepress/plugin-blog": "^1.0.0-alpha.35",
    "@vuepress/plugin-google-analytics": "^1.0.0-alpha.0",
    "@vuepress/plugin-medium-zoom": "^1.0.0-alpha.35",
    "@vuepress/plugin-nprogress": "^1.0.0-alpha.35",
    "date-fns": "^1.30.1",
    "geopattern": "^1.2.3",
    "lodash.debounce": "^4.0.8",
    "lodash.throttle": "^4.1.1",
    "vuepress": "^1.0.0-alpha.48",
    "vuepress-plugin-container": "^1.1.1",
    "vuepress-plugin-mathjax": "^1.2.4",
    "vuepress-plugin-nprogress": "^1.0.0",
    "vuepress-plugin-smooth-scroll": "^0.0.3",
    "vuepress-plugin-zooming": "^1.0.0",
    "vuepress-theme-meteorlxy": "^1.0.0-alpha.38"
  },
  "devDependencies": {
    "cross-env": "^5.2.0",
    "vuepress-plugin-baidu-autopush": "^1.0.1",
    "vuepress-plugin-sitemap": "^2.1.1"
  }
}
```

**Comment by moyu-x** [comment]
when I upgrade the vuepress to v1.0.0, I have the same problem, and my config is same to you. I use global install cant no resolve the problem.

**Comment by shigma** [comment]
@ChungZH @idwangmo I have just released a new version `1.2.8`. Does it solve your problem?

**Comment by moyu-x** [comment]
@Shigma I upgrade 1.2.8 solved it. Thank you.

**Comment by belvederef** [comment]
The `[vuepress]: cannot resolve plugin "mathjax"` problem persists with Vuepress version 1.0.3 and the latest version of this package (`1.2.8`). Downgrading to vuepress `1.0.0` solved the problem, though.
